applicationName: 'AppECS-photo-album-cluster-photo-album-service'
deploymentGroupName: 'DgpECS-photo-album-cluster-photo-album-service'
revision:
  revisionType: AppSpecContent
  appSpecContent:
    content: |
      version: 0.0
      Resources:
        - TargetService:
            Type: AWS::ECS::Service
            Properties:
              TaskDefinition: "arn:aws:ecs:us-east-1:677276083056:task-definition/photo-album-td:15"
              LoadBalancerInfo:
                ContainerName: photo-album-container
                ContainerPort: 3000
