export enum PhotoCategories {
    All = "All",
    Anime = "Anime",
    Nature = "Nature",
    Animals = "Animals",
    Architecture = "Architecture",
    People = "People",
    Technology = "Technology",
    Food = "Food",
    Travel = "Travel",
    Sports = "Sports",
    Fashion = "Fashion",
    Art = "Art",
    Music = "Music",
    Business = "Business",
    Health = "Health",
    Science = "Science",
    Education = "Education",
    Entertainment = "Entertainment",
    History = "History",
    Lifestyle = "Lifestyle",
    Gaming = "Gaming",
    Pets = "Pets",
    Other = "Other",
}
